#!/bin/bash
clear
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mPLEASE WAIT... \033[1;37m- \033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mPLEASE WAIT... \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo '                                                              
    ██████╗ ███████╗██╗  ██╗████████╗███████╗██████╗        
    ██╔══██╗██╔════╝╚██╗██╔╝╚══██╔══╝██╔════╝██╔══██╗       
    ██║  ██║█████╗   ╚███╔╝    ██║   █████╗  ██████╔╝       
    ██║  ██║██╔══╝   ██╔██╗    ██║   ██╔══╝  ██╔══██╗       
    ██████╔╝███████╗██╔╝ ██╗   ██║   ███████╗██║  ██║       
    ╚═════╝ ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝  ╚═╝       
'
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo ""
echo -e "UPDATING PACKAGE LIST..."
fun_att () {
apt update && apt upgrade -y
}
fun_bar 'fun_att'
echo -e "INSTALLING AND UPDATING REQUIRED PACKAGES..."
install_pkgs () {
apt install screen -y
apt install cron -y
apt install iptables -y
service cron reload
service cron restart
service iptables reload
service iptables restart
}
fun_bar 'install_pkgs'
echo -e "CONFIGURING IPTABLES..."
ipt_set () {
cd /etc
mv rc.local rc.local.bkp
wget https://github.com/xamjyss143/slow-dns/raw/main/rc.local
chmod +x /etc/rc.local
systemctl enable rc-local
systemctl start rc-local
}
fun_bar 'ipt_set'
clear
echo ""
echo -e "\033[1;31m ATTENTION AT THIS STEP! \033[1;33m"
echo ""
cd
nameserver=$(<nameserver.txt)
cd /etc/slowdns
touch infons
echo $nameserver > infons
set_ns () {
sleep 1
wget https://raw.githubusercontent.com/leitura/slowdns/main/ssh/startdns 
wget https://raw.githubusercontent.com/leitura/slowdns/main/ssh/restartdns
chmod +x startdns
chmod +x restartdns
sed -i "s;1234;$nameserver;g" /etc/slowdns/startdns > /dev/null 2>&1
sed -i "s;1234;$nameserver;g" /etc/slowdns/restartdns > /dev/null 2>&1
cp startdns /bin/
cp restartdns /bin/
}
fun_bar 'set_ns'
echo ""
echo "Checking for existence of key"
sleep 2
echo ""
echo "      Please wait...   "
sleep 2
cd
key1="/root/server.key"
key2="/root/server.pub"
if [ -f $key1 ] && [ -f $key2 ]
then
echo -e "Key file found!"
sleep 1
echo ""
key () {
echo "How do you want to get your key?"
echo ""
echo "[ 1 ] | Use existing key in file"
echo "[ 2 ] | Delete file and generate new key"
echo "[ 3 ] | Delete file and use default key"
echo "[ x ] | Abort installation"
echo ""
echo -ne "enter an option: " && read opcao
case $opcao in
1) Opcao1 ;;
2) Opcao2 ;;
3) Opcao3 ;;
x) OpcaoX ;;
*) "unknown command" ; echo ; key;;
esac
}
Opcao1 () {
echo -ne "Restoring existing key..." && sleep 2 && echo "OK!"
echo ""
echo -e "FINISHING..."
finish_ist () {
cd /etc/slowdns
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m INSTALLATION COMPLETE!\033[0m"
echo ""
echo -ne "\033[1;33mYOUR Domain/NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mYOUR KEY:\033[0m " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mCOMMAND TERMUX:\033[0m curl -sO https://raw.githubusercontent.com/xamjyss143/slow-dns/main/scripts/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33m YOUR KEY is saved in the file /root/server.pub\033[0m"
echo -e "\033[1;33mKeep it in a safe place, you might need it in the future!\033[0m"
echo ""
}
Opcao2 () {
cd
rm server.key server.pub
echo "Generating new key"
cd /etc/slowdns/
./dns-server -gen-key -privkey-file /root/server.key -pubkey-file /root/server.pub
echo -e "FINISHING..."
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
cd
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m INSTALLATION COMPLETE!\033[0m"
echo ""
echo -ne "\033[1;33mYOUR Domain/NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mYOUR KEY:\033[0m " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mCOMMAND TERMUX:\033[0m curl -sO https://raw.githubusercontent.com/xamjyss143/slow-dns/main/scripts/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33m YOUR KEY is saved in the file /root/server.pub\033[0m"
echo -e "\033[1;33mKeep it in a safe place, you might need it in the future!\033[0m"
echo ""
}
Opcao3 () {
echo -e "Downloading default key pair..."
cd
rm server.key server.pub
wget https://raw.githubusercontent.com/xamjyss143/slow-dns/main/server.key
wget https://raw.githubusercontent.com/xamjyss143/slow-dns/main/server.pub
sleep 1
echo -e "Download Completed"
sleep 1
cd /etc/slowdns/
echo -e "FINISHING..."
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
cd
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m INSTALLATION COMPLETE!\033[0m"
echo ""
echo -ne "\033[1;33mYOUR Domain/NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mYOUR KEY:\033[0m " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mCOMMAND TERMUX:\033[0m curl -sO https://raw.githubusercontent.com/xamjyss143/slow-dns/main/scripts/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33m YOUR KEY is saved in the file /root/server.pub\033[0m"
echo -e "\033[1;33mKeep it in a safe place, you might need it in the future!\033[0m"
echo ""
}
OpcaoX () {
exit
}
key
else
echo -e "There is no key in the records."
echo ""
key_gen () {
echo "How do you want to get your key?"
echo ""
echo "[ 1 ] | Generate on installation"
echo "[ 2 ] | Use the default key"
echo "[ x ] | Abort installation"
echo ""
opc_key1
}
opc_key1 () {
echo "Generating your key..."
cd /etc/slowdns/
./dns-server -gen-key -privkey-file /root/server.key -pubkey-file /root/server.pub
echo -e "FINISHING..."
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
cd
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m INSTALLATION COMPLETE!\033[0m"
echo ""
echo -ne "\033[1;33mYOUR Domain/NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mYour KEY:\033[0m " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mCOMMAND TERMUX:\033[0m curl -sO https://raw.githubusercontent.com/xamjyss143/slow-dns/main/scripts/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33m YOUR KEY is saved in the file /root/server.pub\033[0m"
echo -e "\033[1;33mKeep it in a safe place, you might need it in the future!\033[0m"
echo ""
}
opc_key2 () {
echo -e "Downloading default key pair..."
cd
wget https://raw.githubusercontent.com/xamjyss143/slow-dns/main/server.key
wget https://raw.githubusercontent.com/xamjyss143/slow-dns/main/server.pub
sleep 1
echo -e "Download Completed"
sleep 1
cd /etc/slowdns/
echo -e "FINISHING..."
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
cd
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m INSTALLATION COMPLETE!\033[0m"
echo ""
echo -ne "\033[1;33mYOUR Domain/NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mYOUR KEY:\033[0m " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mCOMMAND TERMUX:\033[0m curl -sO https://raw.githubusercontent.com/xamjyss143/slow-dns/main/scripts/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33m YOUR KEY is saved in the file /root/server.pub\033[0m"
echo -e "\033[1;33mKeep it in a safe place, you might need it in the future!\033[0m"
echo ""
}
opc_keyx () {
echo "Aborting installation"
sleep 2
slowdns
}
key_gen
fi
