#!/bin/bash

# Regular Colors
Black="\[\033[0;30m\]"        # Black
Red="\[\033[0;31m\]"          # Red
Green="\[\033[0;32m\]"        # Green
Yellow="\[\033[0;33m\]"       # Yellow
Blue="\[\033[0;34m\]"         # Blue
Purple="\[\033[0;35m\]"       # Purple
Cyan="\[\033[0;36m\]"         # Cyan
White="\[\033[0;37m\]"        # White

echo -e "\033[1;31m═══════════════════════════════════════════════════\033[0m"
echo '                                                                  
███╗   ███╗████████╗██╗  ██╗    ██╗   ██╗██████╗ ███╗   ██╗
████╗ ████║╚══██╔══╝██║ ██╔╝    ██║   ██║██╔══██╗████╗  ██║
██╔████╔██║   ██║   █████╔╝     ██║   ██║██████╔╝██╔██╗ ██║
██║╚██╔╝██║   ██║   ██╔═██╗     ╚██╗ ██╔╝██╔═══╝ ██║╚██╗██║
██║ ╚═╝ ██║   ██║   ██║  ██╗     ╚████╔╝ ██║     ██║ ╚████║
╚═╝     ╚═╝   ╚═╝   ╚═╝  ╚═╝      ╚═══╝  ╚═╝     ╚═╝  ╚═══╝  
'
echo -e "\033[1;31m═══════════════════════════════════════════════════\033[0m"

echo -e "\033[1;31m Starting Script Withiin 5 Seconds\033[0m"
sleep 5

function autoreboot() {
  echo "[Unit]
 Description=Scheduled Reboot

 [Service]
 Type=oneshot
 ExecStart=/usr/bin/systemctl --force reboot" >> /etc/systemd/system/sched-reboot.service
 
 echo "[Unit]
 Description=Reboot Scheduling

 [Timer]
 OnCalendar=*-*-* 4:00:00

 [Install]
 WantedBy=multi-user.target" >> /etc/systemd/system/sched-reboot.timer

 sudo systemctl enable sched-reboot.timer
 sudo systemctl start sched-reboot.timer
}
autoreboot

echo -e " "
echo -e " "
echo -e " \e[92m MTK AUTO REBOOT INSTALLER\e[0m \e[97m\e[0m"
echo -e " "
echo -e " \e[92m VPS Active\e[0m \e[97m\e[0m"
echo -e " \e[92m Vps Reboot:\e[0m \e[97m:  5 Seconds\e[0m"
sleep 5
reboot
